"""Write the focused Run 018 cross-platform byte-canonicalization report."""
from __future__ import annotations
import argparse,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/"outputs/provisional/release/run_018";REPORT=ROOT/"outputs/provisional/MODEL_INDEPENDENT_NOT_RODRIGUEZ_REPLICATION_RUN_018_CI_PORTABILITY_CORRECTION_ONLY.md"
LABELS=("MODEL_INDEPENDENT","NOT_RODRIGUEZ_REPLICATION","RUN_018","CI_PORTABILITY_CORRECTION_ONLY")
def _head_manifest():
    path="outputs/provisional/release/run_018/semantic-release-manifest.json";raw=subprocess.run(["git","show",f"HEAD:{path}"],cwd=ROOT,check=True,capture_output=True).stdout;return json.loads(raw)
def run(test_result:str,clean_checkout_status:str):
    renorm=json.loads((OUT/"line-ending-renormalization-audit.json").read_text(encoding="utf-8"));current=json.loads((OUT/"semantic-release-manifest.json").read_text(encoding="utf-8"));old=_head_manifest();integrity=json.loads((OUT/"integrity-report.json").read_text(encoding="utf-8"));package=json.loads((OUT/"package-content-report.json").read_text(encoding="utf-8"))
    auth_unchanged=old["semantic_manifest"]["authorization_ledger_hash"]==current["semantic_manifest"]["authorization_ledger_hash"]
    ready=(renorm["audit_status"]=="LINE_ENDING_RENORMALIZATION_OK" and renorm["all_binary_artifacts_byte_identical"] and renorm["all_renormalized_text_content_equal"] and integrity["status"]=="RELEASE_INTEGRITY_OK" and package["build_status"]=="PACKAGE_BUILD_OK" and clean_checkout_status=="PASS" and auth_unchanged)
    gate="RUN_018_CROSS_PLATFORM_RELEASE_INTEGRITY_GO" if ready else "RUN_018_CROSS_PLATFORM_RELEASE_INTEGRITY_REFINEMENT_REQUIRED"
    payload={"labels":LABELS,"gate":gate,"root_cause":"Windows working-tree CRLF conversion made raw-byte protected hashes differ from canonical LF Git blobs and Ubuntu checkout bytes.","renormalized_text_file_count":renorm["changed_path_count"],"binary_artifacts_byte_identical":renorm["all_binary_artifacts_byte_identical"],"parsed_and_normalized_content_equal":renorm["all_renormalized_text_content_equal"],"readme_formatting_correction":"documentation-only nested code fence removed","previous_release_hash":old["semantic_hash"],"new_release_hash":current["semantic_hash"],"authorization_ledger_unchanged":auth_unchanged,"test_result":test_result,"integrity_result":integrity["status"],"package_build_result":package["build_status"],"clean_canonical_checkout":clean_checkout_status,"scientific_content_changed":False,"authorization_boundaries_changed":False,"raw_byte_hashing_retained":True,"force_evaluations":0,"force_cache_rebuilds":0,"trajectory_integrations":0,"capture_calculations":0,"optimization_runs":0}
    (OUT/"ci-portability-correction-audit.json").write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n",encoding="utf-8",newline="\n")
    REPORT.write_text("\n".join(["# MODEL_INDEPENDENT NOT_RODRIGUEZ_REPLICATION RUN_018 CI_PORTABILITY_CORRECTION_ONLY","",f"Root cause: {payload['root_cause']}","",f"Renormalized working-tree text files: `{payload['renormalized_text_file_count']}`. Binary artifacts changed: `0`. Parsed/normalized content equality: `{payload['parsed_and_normalized_content_equal']}`.",f"New release hash: `{payload['new_release_hash']}`. Tests: `{test_result}`. Integrity: `{payload['integrity_result']}`. Clean LF checkout: `{clean_checkout_status}`.","","Authorization boundaries are unchanged. No scientific content changed. No force, cache rebuild, trajectory, capture, optimizer, training, or hardware path ran.","",gate])+"\n",encoding="utf-8",newline="\n");print(gate);return payload
if __name__=="__main__":
    p=argparse.ArgumentParser();p.add_argument("--test-result",required=True);p.add_argument("--clean-checkout-status",choices=("PASS","FAIL","PENDING"),required=True);a=p.parse_args();run(a.test_result,a.clean_checkout_status)
